### ISSUE TITLE
BUG - Affichage du menu au clic sur le logo

### ISSUE THREAD

**Issue by johannygrenier** [ecvdbdx1617/Odezenne#170]
Lorsque l'on clique sur le LOGO, le menu s'ouvre ce qui est bizarre 😄
Juste faire qu'il renvoit à l'accueil sera parfait. 

Merci !

**Comment by Bramvanosta** [comment]
Nope, c'est le comportement demandé vu qu'il n'y a pas vraiment de home.

**Comment by johannygrenier** [comment]
Yep on a vu avec Jonas, Désolé les amis ! :)
